apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nxp-ui-template.fullname" . }}
  labels:
    {{ include "nxp-ui-template.labels" . | nindent 4 }}
data:
  VUE_APP_NXP_EAAS_URL: "{{ .Values.project.eaasUrl }}"
  VUE_APP_NXP_TRACING_URL: "{{ .Values.project.tracingUrl }}"
  VUE_APP_KEYCLOAK_URL: "{{ .Values.project.keycloakUrl }}"
  VUE_APP_KEYCLOAK_REALM: "{{ .Values.project.keycloakRealm }}"
  VUE_APP_KEYCLOAK_CLIENT_ID: "{{ .Values.project.keycloakClientId }}"
